### ISSUE TITLE
ERROR #11321  PLUGIN 

### ISSUE THREAD

**Issue by danieladarve** [craftcms/gatsby-source-craft#10]
### Description
Upon running gatsby develop, im getting the following error
```
ERROR #11321  PLUGIN

"gatsby-source-craft" threw an error while running the onPreBootstrap lifecycle:

Only absolute URLs are supported

  237 |         headers['X-Craft-Token'] = previewToken;
  238 |     }
> 239 |     const res = await fetch(craftGqlUrl, {
      |                       ^
  240 |         method: "POST",
  241 |         body: JSON.stringify({ query, variables, operationName }),
  242 |         headers

File: node_modules/gatsby-source-craft/gatsby-node.js:239:23

  TypeError: Only absolute URLs are supported
```

ENV variables are set as specified in the DOCS
```
CRAFTGQL_TOKEN=_VOTTQWBP1bx19gQLE1gBynzz
CRAFTGQL_URL=https://testsite.test/api
```
and the plugin is listed in gatsby-config.js

### Additional info

- Craft version: Craft Pro 3.5.15.1
- PHP version: 7.4.10
- Database driver & version: MySQL 5.7.32
- Plugins & versions:
- Node v11.15.0

**Comment by BasitEllahi** [comment]
i have the same issue

**Comment by BasitEllahi** [comment]
Im getting this error when i do the command gatsby build

**Comment by danieladarve** [comment]
> i have the same issue, but it's working now.

Did you change anything?
Seems to be related to the environment variables and how the are loaded at run time.
https://www.gatsbyjs.com/docs/environment-variables/

**Comment by danieladarve** [comment]
For anyone having this issue, you need to make sure the environment file is being loaded in gastby-config.js a per https://www.gatsbyjs.com/docs/environment-variables/
