### ISSUE TITLE
Cannot get it to work with Gatsby v5^

### ISSUE THREAD

**Issue by delasign** [craftcms/gatsby-source-craft#112]
### Description
I cannot manage to get the plugin to work with Gatsby V5.0.0^. It says that it's incompatible.

### Steps to reproduce

1. Create a new Gatsby project.
2. Follow the instructions to setup the gatsby-source-craft.
3. Fill in some queries
4. Attempt to build.

### Additional info

- Craft version: Craft Pro 4.4.15
- PHP version: 8.0.28
- Database driver & version: MySQL 8.0.31
- Plugins & versions:

Amazon S3 | 2.0.3
Field Manager | 3.0.6
Mail Service (Custom, Non Released Plugin) | 1.0.0
Redactor | 3.0.4
Remote Sync | 4.1.1
Super Table | 3.0.9
Gatsby Helper |  2.0.1

**Comment by delasign** [comment]
More details:

warn Plugin gatsby-source-craft is not compatible with your gatsby version 5.11.0 - It
requires gatsby@^4.0.0

"gatsby-source-craft" threw an error while running the onPluginInit lifecycle:

Schema introspection failed. First error:

  45 | async function getSchema() {
  46 |     if (!schema) {
> 47 |         schema = await loadSchema(execute);
     |                  ^
  48 |     }
  49 |     return schema;
  50 | }

**Comment by delasign** [comment]
I tried to play with the way the Token is written (removing the Authorization: (Failed) and Authorization: Bearer - it led to this.

 ERROR  UNKNOWN

Unable to source nodes!


 ERROR #11321  API.NODE.EXECUTION

"gatsby-source-craft" threw an error while running the createSchemaCustomization lifecycle:

ENOENT: no such file or directory, scandir
'.../gatsby/delasign/node_
modules/gatsby-source-craft/.cache/internal-craft-fragments'



  Error: ENOENT: no such file or directory, scandir '.../gatsby/delasign/node_modules/gatsby-source-craft/.cache/inter
  nal-craft-fragments'

success createSchemaCustomization - 0.027s

 ERROR  UNKNOWN

Unable to source nodes!


 ERROR #11321  API.NODE.EXECUTION

"gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

ENOENT: no such file or directory, scandir
'.../gatsby/delasign/node_
modules/gatsby-source-craft/.cache/internal-craft-fragments'



  Error: ENOENT: no such file or directory, scandir '.../gatsby/delasign/node_modules/gatsby-source-craft/.cache/inter
  nal-craft-fragments'

warn The gatsby-source-craft plugin has generated no Gatsby nodes. Do you need it? This could
also suggest the plugin is misconfigured.

**Comment by brianjhanson** [comment]
Sorry @delasign the Gatsby source plugin does not currently support Gastby 5.0. 4.X versions of Gatsby should work though.

**Comment by delasign** [comment]
@brianjhanson I just downgraded to Gatsby v4.20.0 and tried again and I am having the exact same problems.

**Comment by delasign** [comment]
Got it working on v5.11 of Gatsby. Tutorial coming on how to coming soon.

**Comment by delasign** [comment]
https://delasign.com/blog/gatsby-craft-cms-source-plugin

**Comment by westsidetechsolutions** [comment]
Will we get support for Gatsby 5 on this project?
