### ISSUE TITLE
Live Preview 404 when attempting to update

### ISSUE THREAD

**Issue by mcclaskiem** [craftcms/gatsby-source-craft#17]
### Description
I currently have a "preview" server that is running `gatsby develop` on Digital Ocean's App Platform. This runs fine with no issues and also has the `ENABLE_GATSBY_REFRESH_ENDPOINT` set to `true`. I have taken the `baseUrl` for this app and added it to the Gatsby Helper settings within my Craft CMS install as stated in the documentation. When I am using the Live Preview feature within the CMS, everytime I make an update the AJAX request to trigger an update within Gatsby results in a 404 Error, nothing is logged by Gatsby, and no changes are made.

After some digging I went into the Gatsby Helper settings and have changed the URL there from the `{baseUrl}` to `{baseUrl}/__refresh` which is the direct url of webhook endpoint for Gatsby to trigger an update.

After making this change, I know get a 200 status back on the update request but do not see any changes reflected in the Live Preview.

**Request Payload:**
```
id: 3
operation: "update"
siteId: 1
token: "asdjkasjdh23122"
typeName: "home_home_Entry"
```

**Response:**
The browser is currently showing no response available to this request, unsure if that is expected or not.

**Server Logs:**
On the "preview" server I can see the logs firing whenever this update request is made however there is an error happening during the `sourceNodes` lifecycle, pasted below:

`FetchError: invalid json response body at https://gencon-admin-staging.thesmithy.io/actions/graphql/api reason: Unexpected token < in JSON at position 4`

_This does not seem to break the app as the preview remains properly rendered._

**Note:** For some reason the only endpoint that will work for me is `actions/graphql/api`. Even after updating my `routes.php` file, both `api` and `graphql/api` do not work. Maybe it's a server thing? (Separate issue for me to sort out). I actually get the invalid json response body error as stated above. My assumption is that its getting the 404 html page back. But since this endpoint works to initially source the website I am not sure why this breaks on update.

### Steps to reproduce

1. Add baseurl for preview to Gatsby Helper
2. Open Live Preview on an entry
3. Observer no changes to content and 404 in console

### Additional info

Craft version: 3.5.17.1
PHP version: 7.4
Database driver & version:
Plugins & versions:
"gatsby": "^2.29.3",
"gatsby-source-craft": "^1.0.0-beta.2",
"gatsby-source-graphql": "^2.5.3",

**Comment by andris-sevcenko** [comment]
> FetchError: invalid json response body at https://gencon-admin-staging.thesmithy.io/actions/graphql/api reason: Unexpected token < in JSON at position 4

This sounds like a PHP error being thrown. Can you check your Craft log files?

If on Gatsby end you see some reaction whenever you hit the `__refresh` endpoint, it would indicate that Gatsby is configured correctly.

Seeing as how you're also experiencing routing issues, might be environmental. So, again, can you check Craft log files to see if there's anything relevant there?

**Comment by mcclaskiem** [comment]
@andris-sevcenko Below is the stack trace from `web-404s.log` Looks like it thinks it is a template when updating the site but not when originally sourcing it.

```
2021-01-06 11:39:49 [-][-][-][trace][craft\web\UrlManager::_getMatchedElementRoute] [
    'rule' => 'Element URI: actions/graphql/api',
    'match' => false,
    'parent' => null,
]
2021-01-06 11:39:49 [-][-][-][trace][craft\web\UrlManager::_getMatchedDiscoverableUrlRoute] [
    'rule' => 'Discoverable change password URL',
    'match' => false,
    'parent' => null,
]
2021-01-06 11:39:49 [-][-][-][trace][craft\web\UrlManager::_getTemplateRoute] [
    'rule' => 'Template: actions/graphql/api',
    'match' => true,
    'parent' => null,
]
2021-01-06 11:39:49 [-][-][-][trace][yii\web\Application::handleRequest] Route requested: 'templates/render'
2021-01-06 11:39:49 [-][-][-][trace][yii\base\Controller::runAction] Route to run: templates/render
2021-01-06 11:39:49 [-][-][-][trace][yii\base\InlineAction::runWithParams] Running action: craft\controllers\TemplatesController::actionRender()
2021-01-06 11:39:49 [-][-][-][error][yii\web\HttpException:404] yii\web\NotFoundHttpException: Template not found: actions/graphql/api in /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/controllers/TemplatesController.php:92
Stack trace:
#0 [internal function]: craft\controllers\TemplatesController->actionRender()
#1 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#2 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#3 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#4 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#5 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#6 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#7 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Application.php(144): yii\web\Application->handleRequest()
#8 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/controllers/PreviewController.php(134): craft\web\Application->handleRequest()
#9 [internal function]: craft\controllers\PreviewController->actionPreview()
#10 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#11 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#12 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#13 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#14 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#15 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#16 /home/forge/gencon-admin-staging.thesmithy.io/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#17 /home/forge/gencon-admin-staging.thesmithy.io/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#18 /home/forge/gencon-admin-staging.thesmithy.io/web/index.php(22): yii\base\Application->run()
#19 {main}
```

**Comment by andris-sevcenko** [comment]
I think the main thing to do here is to get your routes working correctly and go from there. Can you get in touch over support@craftcms.com, send over your routes.php file and reference this issue, please?

**Comment by mcclaskiem** [comment]
@andris-sevcenko I have sent an email to Craft support. Thanks!

**Comment by mcclaskiem** [comment]
I actually opted to investigate further and figured out the routes issue but am now getting CORS errors due to one of the headers included with the POST to Gatsby:

`Request header field x-preview-update-source is not allowed by Access-Control-Allow-Headers in preflight response.` I also get the same error for "Content-type" not sure if its a case-sensitive thing or not since the helper plugin uses:

`http.setRequestHeader('Content-type', 'application/json');`

I am using Digital Ocean's App Platform for hosting, which does not have full control of headers as it pertains to CORS. If I comment out both of the header sets in the helper plugin:

```
http.setRequestHeader('Content-type', 'application/json');
http.setRequestHeader('x-preview-update-source', 'Craft CMS');
```

I can get the request to go through and I see my gatsby logs update, however, `reporter.info("Processing webhook.");` never fires and nothing changes. Which leads me to think that that header is required to Gatsby to know it needs to update? I am going to keep digging on how I can customize things within Digital Ocean but wanted to provide an update

**Comment by andris-sevcenko** [comment]
The `Content-type` header is mandatory for it to work. The `X-preview-update-source` is required only if you're doing this on Gatsby Cloud (which you're not).

**Comment by mcclaskiem** [comment]
Ok, I just stood up my site on Gatsby Cloud, got everything wired up correctly and can see a successful `POST` however no changes occur within the CMS. Are there limitation to the live preview based on the type of fields we are using or something else? Seems I can't win this week with Gatsby + Craft

**Comment by andris-sevcenko** [comment]
> I am going to work on getting my Digital Ocean App to allow "Content-Type" header but was wondering if it is possible to make the X-preview-update-source optional so that a user not using Gatsby Cloud does not run into issue. I will see if I can also add non-standard headers to their platform to allow the X-preview to just not cause issues as well.

Since the `Content-Type` header is mandatory, so making the `x-preview` header optional would still not solve the problem on the Digital Ocean App platform.

**Comment by mcclaskiem** [comment]
I was able to circumvent the CORS issues after working with the DO Engineering Team. Everything seems to be working fine now!

**Comment by andris-sevcenko** [comment]
Glad to hear it! Was it something that you had to configure on your end? Can you, perhaps, share what steps you had to take in case somebody else runs across this?

**Comment by wagybwoi** [comment]
Any updates on how you managed to circumvent the 404? I'm currently running into this issue. `gatsby-source-craft` receives a 404 response every time a live preview update is requested.

```
invalid json response body at https://prideam-temp.frb.io/actions/graphql/api reason: Unexpected token < in JSON at position 0

  291 |     // Aaaand remove the token for subsequent requests
  292 |     previewToken = null;
  293 |     return await res.json();
              |            ^
  294 | }
  295 | exports.onPreBootstrap = async (gatsbyApi, pluginOptions) => {
  296 |     var _a, _b, _c, _d, _e, _f, _g;`
```

**Comment by mcclaskiem** [comment]
Sorry I never got back to updating this.

@wagybwoi The 404 issue I was having originated because the refresh URL within the Gatsby Helper plugin was pointed at the root domain when it needs to be pointed at the webhook URL which is `{siteUrl}/__refresh`. After updating that I was able to get 200 requests. 

The error you are getting seems to be related to the routing on your craft install. I had a similar issue and it was because i was using backticks `` instead of normal '' inside of my `routes.php` file. It looks like you are pointing it directly at the actions url so you may want to check your 404 log file inside of `storage/` to see what the exact error message is on the Craft side.
