### ISSUE TITLE
Error while running the createResolvers lifecycle

### ISSUE THREAD

**Issue by ken-gladeye** [craftcms/gatsby-source-craft#18]
### Description
I got the error when running either `gatsby develop` or `gatsby build`

```
"gatsby-source-craft" threw an error while running the createResolvers lifecycle:

Cannot read property 'name' of undefined

  382 |     const ifaceName = loadedPluginOptions.typePrefix + 'AssetInterface';
  383 |     const iface = intermediateSchema.getType(ifaceName);
> 384 |     const possibleTypes = intermediateSchema.getPossibleTypes(iface);
      |                                              ^
  385 |     const resolvers = {};
  386 |     for (const assetType of possibleTypes) {
  387 |         resolvers[assetType] = {
```

### Steps to reproduce

1. Install and configure the plugin as per the doc
```js
{
    resolve: `gatsby-source-craft`,
    options: {},
},
```
2. Either run `gatsby develop` or `gatsby build`

### Additional info

- Craft version: 3.5.17.1
- PHP version: 7.4.13
- Database driver & version: MYSQL 5.7.28
- Plugins & versions: 1.0.0-beta.2

**Comment by ken-gladeye** [comment]
Okay, so the workaround is setup a dummy asset volume and enable it in the graphql schema, then the error goes away.

**Comment by andris-sevcenko** [comment]
@ken-gladeye it's still a bug, though. It's on my list to fix this, but thank you for sharing a workaround!

**Comment by andris-sevcenko** [comment]
Alright, just fixed this for the next release. Thanks for reporting!

**Comment by ken-gladeye** [comment]
Awesome, thank you!
