### ISSUE TITLE
site only returns {data: {ping: pong}}

### ISSUE THREAD

**Issue by dbvisel** [craftcms/gatsby-source-craft#20]
I'm trying to get this to work on a Craft site and keep running into an error in Gatsby:

```
ERROR #11321  PLUGIN

"gatsby-source-craft" threw an error while running the onPreBootstrap lifecycle:

Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was
returned alongside: { ping: "pong" }

  36 | async function getSchema() {
  37 |     if (!schema) {
> 38 |         schema = await loadSchema(execute);
     |                  ^
  39 |     }
  40 |     return schema;
  41 | }

File: node_modules/gatsby-source-craft/gatsby-node.js:38:18
```

GraphiQL works fine from inside Craft; but I can't get anything into Gatsby. Any ideas what could be going on here? I will note that if I do a curl from the command line:

```
curl -H "Content-Type: application/graphql" --data-urlencode "query={configVersion}" [url]
```

I don't get back the value for "configVersion" but instead '{"data":{"ping":"pong"}}'. Maybe this isn't a gatsby-source-craft issue? But I'm at a loss.

**Comment by andris-sevcenko** [comment]
In the `curl` example you added you're not providing any authorization token, so Craft will use the public GraphQL schema defined, which defaults to pretty much nothing IIRC.

Have you [set up your schemas and tokens](https://craftcms.com/docs/3.x/graphql.html#define-your-schemas) so Craft knows what content to serve?

**Comment by dbvisel** [comment]
I have set up schemas & tokens, but I'm getting the same thing (even sending curls with headers). I feel like I'm missing something obvious, but I haven't figured out what it is yet – thanks!

**Comment by andris-sevcenko** [comment]
When querying from inside of GraphiQL, Craft uses a different header instead of the `Authorization` header.

Is it possible that your web server configuration is stripping out the header?

**Comment by dbvisel** [comment]
Turns out that was what was happening! Sorry to bother you with this.

**Comment by andris-sevcenko** [comment]
@dbvisel no problem at all - it was not an obvious solution :)
