### ISSUE TITLE
image querying problem

### ISSUE THREAD

**Issue by dbvisel** [craftcms/gatsby-source-craft#25]
### Description

I'm getting an error in Gatsby with certain image files that I've uploaded as a Craft asset that I'm trying to pull in to use as local files. Here's an example:

```
ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unexpected error value: "url passed to createRemoteFileNode is either missing or not a proper web uri: http://alserkalnew.demoyourprojects.com/assets/images/Phantasmagoria’s-Illumination-in-DisenchantmentCurated-by-Dr.-Arshiya-Lokhandwala_installation_5e6de3d3163d4.png"

  230 |       id
  237 |       headerImage {
  238 |         __typename
  239 |         ... on Craft_editorialAssets_Asset {
> 240 |           cardImage: localFile {
      |           ^
  241 |             publicURL
  242 |             childImageSharp {
  243 |               fixed(width: 290) {
  244 |                 src
  245 |                 ...GatsbyImageSharpFixed
```

That particular image URL works – you can click on it. However, it's triggering an error – this is fine in dev, though it crashes Netlify builds.

I'm not 100% sure that this is a gatsby-source-craft issue! And I suspect it might not be! But errors seem to pop up with  mildly strange characters in filenames, like that right single-quote in that file name. When I re-upload the image and give it a safe name ("resavedphantasmagoria.png"), there's no problem with the build. Is this some kind of weird encoding issue? Or do I have something dumb not set in my Craft config?

Thanks so much!

### Additional info

- Craft version: Craft Pro 3.6.7
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.33
- Plugins & versions: Gatsby Helper 1.0.0-beta.2, Redator 2.8.5

**Comment by andris-sevcenko** [comment]
This is definitely not something set by a config option. After some googling around seems to be something that this plugin can mitigate. Give ma a few :)

**Comment by andris-sevcenko** [comment]
Just pushed a fix for this to the `develop` branch. Going to cut the 1.0.0 release this week!

**Comment by dbvisel** [comment]
Oh fantastic! Thank you so much! I really appreciate this.
