### ISSUE TITLE
crash on netlify deploy after adding new content

### ISSUE THREAD

**Issue by dbvisel** [craftcms/gatsby-source-craft#29]
### Description

I'm getting a periodic failed build on Netlify – it seems to happen after a new piece of content is added, but it's not happening consistently. If I clear the cache and rebuild on Netlify, the problem goes away. But here's what's reported in the logs:

```
4:50:38 PM: error "gatsby-source-craft" threw an error while running the sourceNodes lifecycle:
4:50:38 PM: Node "event_event_Entry" with id "[object Object]" is nullish.
4:50:38 PM:   510 |         }
4:50:38 PM:   511 |         // And source, if needed
4:50:38 PM: > 512 |         await sourceNodeChanges(config, { nodeEvents });
4:50:38 PM:       |         ^
4:50:38 PM:   513 |     }
4:50:38 PM:   514 |     await cache.set(`CRAFT_CONFIG_VERSION`, remoteConfigVersion);
4:50:38 PM:   515 |     await cache.set(`CRAFT_LAST_CONTENT_UPDATE`, remoteContentUpdateTime);
4:50:39 PM: 
4:50:39 PM: 
4:50:39 PM:   Error: Node "event_event_Entry" with id "[object Object]" is nullish.
4:50:40 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
4:50:39 PM:   
4:50:39 PM:   - fetch-nodes.ts:21 Object.fetchNonNullishNodesById
4:50:39 PM:     [repo]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/fetch-no    des.ts:21:13
4:50:39 PM:   
4:50:39 PM:   - create-nodes.ts:13 Object.createNodes
4:50:39 PM:     [repo]/[gatsby-graphql-source-toolkit]/src/source-nodes/node-actions/create-    nodes.ts:13:20
4:50:39 PM:   
4:50:39 PM:   - async Promise.all
4:50:39 PM:   
4:50:39 PM:   - source-node-changes.ts:35 sourceNodeChanges
4:50:39 PM:     [repo]/[gatsby-graphql-source-toolkit]/src/source-nodes/source-node-changes.    ts:35:3
4:50:39 PM:   
4:50:39 PM:   - gatsby-node.js:512 Object.exports.sourceNodes
4:50:39 PM:     [repo]/[gatsby-source-craft]/gatsby-node.js:512:9
4:50:39 PM:   
4:50:39 PM:   - api-runner-node.js:485 runAPI
4:50:39 PM:     [repo]/[gatsby]/src/utils/api-runner-node.js:485:16
4:50:39 PM:   
4:50:39 PM: 
4:50:39 PM: not finished source and transform nodes - 4.251s
```

There what seems to have happened is that a user added a new entry of content type Event, but this doesn't seem to be tied to any particular content type; and this error always goes away when I clear the cache on Netlify. 

I am running the Gatsby Cache plugin on Netlify, and it's possible that's getting in the way of things – I like it because it does bring build times down considerably, but I'm going to try to turn it off to see if it's contributing to this error.

### Steps to reproduce

1. Add new piece of content
2. Try to redeploy
3. . . . and sometimes this happens? But not always!

### Additional info

- Craft version: Craft Pro 3.6.11.2
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

Gatsby Helper 1.0.1
nethooks 1.1.2
Redactor 2.8.5
Webhooks 2.3.2

**Comment by andris-sevcenko** [comment]
Sounds like a duplicate of https://github.com/craftcms/gatsby-helper/issues/13

Can you read through that issue and see if it sounds like it be what you're experiencing?

**Comment by dbvisel** [comment]
Yes! That seems like the same thing, thanks for the pointer.
