### ISSUE TITLE
Custom type field is missing from Gatsby

### ISSUE THREAD

**Issue by sjelfull** [craftcms/gatsby-source-craft#32]
### Description

I have added a custom type field named `imgix` to `AssetInterface` through the `TypeManager::EVENT_DEFINE_GQL_TYPE_FIELDS` event like this:

```php
 Event::on(
            TypeManager::class,
            TypeManager::EVENT_DEFINE_GQL_TYPE_FIELDS,
            function(DefineGqlTypeFieldsEvent $event) {
                if (in_array($event->typeName, self::GQL_ELEMENT_INTERFACES, true)) {
                    $event->fields['imgix'] = [
                        'name' => 'imgix',
                        'type' => ImgixInterface::getType(),
                        'args' => ImgixArguments::getArguments(),
                        'resolve' => ImgixResolver::class . '::resolve',
                        'description' => 'This query is used to query for Imgix meta data.',
                    ];
                }
            });
```

This has been working well with the `gatsby-source-graphql` source, and I have been using it like this: 
```graphql
imgix(maxWidth: 800, maxHeight: 800, quality: 100) {...}
```

After installing `gatsby-source-craft`, I still see the custom type (`imgix`) on `AssetInterface`, but it doesn't list any of the params.

![image](https://user-images.githubusercontent.com/10508/118885928-a2f07580-b8f8-11eb-8eab-a978018b2732.png)

Now, I read the section about [Integrating Third-Party Content](https://github.com/craftcms/gatsby-source-craft#integrating-third-party-content), but this seems to apply only to source nodes?

Do I need to do anything else for the source to pick them up?

### Additional info

- Craft version: 3.6

**Comment by andris-sevcenko** [comment]
As discussed on Discord with @sjelfull - this is best-resolved by using [custom fragments](https://github.com/craftcms/gatsby-source-craft#appending-custom-fragments).
