### ISSUE TITLE
Unknown argument "status" on field "asset" of type "Query"

### ISSUE THREAD

**Issue by thejoshsmith** [craftcms/gatsby-source-craft#35]
### Description
I upgraded to `v1.02` and received the following error upon build (Gatsby Cloud & locally):

<img width="1096" alt="Screen Shot 2021-05-26 at 8 54 39 PM" src="https://user-images.githubusercontent.com/5515179/119632100-9c1bb280-be64-11eb-988b-db43b1efad78.png">

### Steps to reproduce

1. Update to version `v1.02`
2. `npm run build`

### Additional info

- Craft version: 3.6.15
- PHP version: 7.4.11
- Database driver & version: MySQL 5.7.30
- Plugins & versions: 
  -  aelvan/mailchimp-subscribe: 3.0.3
  -  craftcms/commerce: 3.3.2
  -  craftcms/commerce-stripe: 2.3.2.1
  -  craftcms/gatsby-helper: 1.0.1
  -  craftcms/redactor: 2.8.7
  -  nystudio107/craft-seomatic: 3.3.42
  -  putyourlightson/craft-amazon-ses: 1.3.3
  -  vaersaagod/matrixmate: 1.2.7
  -  verbb/super-table: 2.6.8

I can provide Craft project config/composer.json/database if required.

**Comment by andris-sevcenko** [comment]
Appreciate this, Josh!

I'll get this fixed asap.

**Comment by thejoshsmith** [comment]
Cheers mate, appreciate the quick response!

**Comment by andris-sevcenko** [comment]
Just pushed a fix to Craft CMS itself to address this, as the status argument should not have been missing there.

**Comment by brandonkelly** [comment]
Craft 3.6.16 is out now with that fix.
