### ISSUE TITLE
error on build after upgrading to 1.0.2

### ISSUE THREAD

**Issue by dbvisel** [craftcms/gatsby-source-craft#37]
### Description

I have a Craft site that's running an up-to-date Gatsby Helper (1.0.3). I'm still periodically getting crashes on Netlify deploys, which get fixed when I clear the cache and redeploy (what's described here: https://github.com/craftcms/gatsby-helper/issues/13 ). I was going to report an error, but then I took a look at my package.json and realized that my gatsby-source-craft was still at 1.0.0. So I updated to gatsby-source-craft 1.0.2 hoping that this piece of stupidity on my part would fix things. 

This is not the case! After updating to 1.0.2, I can't get a build to work either locally or on Netlify. Here's the trace I get running locally:

```
"gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

Failed to execute query LIST_ourPeople_ourPeople_Entry.
Errors:
Unknown argument "status" on field "entry" of type "Query".

  468 |     if (remoteConfigVersion !== localConfigVersion || !localContentUpdateTime) {
  469 |         reporter.info("Cached content is unavailable or outdated, sourcing _all_ nodes.");
> 470 |         await sourceAllNodes(config);
      |         ^
  471 |     }
  472 |     else {
  473 |         reporter.info(`Craft config version has not changed since last sourcing. Checking for content changes since 
"${localContentUpdateTime}".`);

File: node_modules/gatsby-source-craft/gatsby-node.js:470:9



  Error: Failed to execute query LIST_ourPeople_ourPeople_Entry.
  Errors:
  Unknown argument "status" on field "entry" of type "Query".
  
  - paginate.ts:60 Object.paginate
    [alserkal-designsystem]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/paginate.ts:60:13
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - fetch-lists.ts:61 fetchNodeList
    [alserkal-designsystem]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/fetch-lists.ts:61:20
  
  - fetch-lists.ts:36 Object.fetchAllNodes
    [alserkal-designsystem]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/fetch-lists.ts:36:24
  
  - create-nodes.ts:13 Object.createNodes
    [alserkal-designsystem]/[gatsby-graphql-source-toolkit]/src/source-nodes/node-actions/create-nodes.ts:13:20
  
  - async Promise.all
  
  - source-all-nodes.ts:20 sourceAllNodes
    [alserkal-designsystem]/[gatsby-graphql-source-toolkit]/src/source-nodes/source-all-nodes.ts:20:3
  
  - gatsby-node.js:470 Object.exports.sourceNodes
    [alserkal-designsystem]/[gatsby-source-craft]/gatsby-node.js:470:9
  
  - api-runner-node.js:485 runAPI
    [alserkal-designsystem]/[gatsby]/src/utils/api-runner-node.js:485:16
  

success fetching discoverTheAvenue_discoverTheAvenue_Entry - 4.243s
warn The gatsby-source-craft plugin has generated no Gatsby nodes. Do you need it?
```

As noted, it looks like nothing's coming in from Craft at all. 

If I downgrade to gatsby-source-craft, the whole thing works again (though I'll presumably still get periodically failing builds). Any idea what could be happening? 

One thing to note: in my schema in Craft, I have:

Allow listing element drafts
Allow listing element revisions
Allow listing non-live and otherwise inactive elements.

all unchecked.

### Steps to reproduce

1. uninstall working gatsby-source-craft 1.0.0, install gatsby-source-craft 1.0.2
2. try to build

### Additional info

- Craft version: Craft Pro 3.6.16
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Gatsby Helper 1.0.3

**Comment by andris-sevcenko** [comment]
> One thing to note: in my schema in Craft, I have:
Allow listing element drafts
Allow listing element revisions
Allow listing non-live and otherwise inactive elements.
all unchecked.

For the schema that Gatsby uses, they definitely should be checked.

**Comment by dbvisel** [comment]
Thanks so much! Working now – I hope my stupidity is helpful to somebody else!

**Comment by Matthaios** [comment]
Hi, 

I have a similar issue although all fields are checked in the schema. 
I'm using Craft Pro 3.6.16. and  gatsby-source-craft@2.0.2. 

This is the error I get. 
`Error: Failed to execute query LIST_products_products_Entry.
  Errors:
  No GraphQL query was supplied`

Any resolution on this? It seems that it's not related only to 1.0.2.

Thanks

**Comment by andris-sevcenko** [comment]
Can you set the `debugDir` plugin setting to, for example, `${__dirname}/craft-debug/`, run the build again and then post the content of `./craft-debug/products_products_Entry.graphql`? Ideally, that all would be posted as a new GitHub issue.

Or, if you prefer, send the contents of that file to support@craftcms.com and refer to this issue?
