### ISSUE TITLE
Sourcing data error

### ISSUE THREAD

**Issue by Matthaios** [craftcms/gatsby-source-craft#38]
### Description
I get errors when trying to local develop and I don't get any nodes back. All fields are checked in Craft so that shouldn't be the problem that the nodes are not getting back.

### Steps to reproduce

1. gatsby develop

### Additional info

- Craft version: Craft Pro 3.6.16
- PHP version: 7.4.14
- Database driver & version:  MySQL 5.7.29
- gatsby-source-craft@^2.0.2

```
 ERROR #11321  PLUGIN

"gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

Failed to execute query LIST_Homepage_Homepage_Entry.
Errors:
No GraphQL query was supplied

  468 |     if (remoteConfigVersion !== localConfigVersion || !localContentUpdateTime) {
  469 |         reporter.info("Cached content is unavailable or outdated, sourcing _all_ nodes.");
> 470 |         await sourceAllNodes(config);
      |         ^
  471 |     }
  472 |     else {
  473 |         reporter.info(`Craft config version has not changed since last sourcing. Checking for content       
changes since "${localContentUpdateTime}".`);

File: node_modules\gatsby-source-craft\gatsby-node.js:470:9



  Error: Failed to execute query LIST_Homepage_Homepage_Entry.
  Errors:
  No GraphQL query was supplied

  - paginate.ts:60 Object.paginate
    [emson-brands-shopify]/[gatsby-source-craft]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/pagina    te.ts:60:13

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

  - fetch-lists.ts:61 fetchNodeList
    [emson-brands-shopify]/[gatsby-source-craft]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/fetch-    lists.ts:61:20

  - fetch-lists.ts:36 Object.fetchAllNodes
    [emson-brands-shopify]/[gatsby-source-craft]/[gatsby-graphql-source-toolkit]/src/source-nodes/fetch-nodes/fetch-    lists.ts:36:24

  - create-nodes.ts:13 Object.createNodes
    [emson-brands-shopify]/[gatsby-source-craft]/[gatsby-graphql-source-toolkit]/src/source-nodes/node-actions/creat    e-nodes.ts:13:20

  - async Promise.all

  - source-all-nodes.ts:20 sourceAllNodes
    [emson-brands-shopify]/[gatsby-source-craft]/[gatsby-graphql-source-toolkit]/src/source-nodes/source-all-nodes.t    s:20:3

  - gatsby-node.js:470 Object.exports.sourceNodes
    [emson-brands-shopify]/[gatsby-source-craft]/gatsby-node.js:470:9

  - api-runner-node.js:434 runAPI
    [emson-brands-shopify]/[gatsby]/src/utils/api-runner-node.js:434:16
```

**Comment by andris-sevcenko** [comment]
Ideally, please select the same schema in the IDE that you're using for Gatsby.

**Comment by Matthaios** [comment]
I get this:

```
{
  "errors": [
    {
      "message": "No GraphQL query was supplied"
    }
  ]
}
```

**Comment by andris-sevcenko** [comment]
Huh. That one is thrown by Craft if there is no query provided. This sounds like an environmental issue with POST being redacted or something? What's your hosting environment?

**Comment by Matthaios** [comment]
Hm... I'm the frontend dev on the project. Will wait for the backend dev if he can provide details.

**Comment by we-do** [comment]
The problem seems to have been with the Apache server configuration and us exceeding the post request size config.

Hope this helps anyone else! :)

**Comment by szymonStawowy94** [comment]
I have the same problem with running gatsby develop. I've got the newest version of Craft (3.6.16), PHP version on server - 7.3.23, gatsby-source-craft plugin version - 2.0.2. Errors which occur:

ERROR #85901  GRAPHQL
There was an error in your GraphQL query:
Unknown type Craft_... (the same error for every single node)

ERROR #85923  GRAPHQL
There was an error in your GraphQL query:
Cannot query field "allCraftCookiesGlobalSet" on type "Query".

It seems that gatsby develop command finishes but I get page without data from CMS and there are no nodes with data. 
Any ideas?

**Comment by andris-sevcenko** [comment]
@szymonStawowy94 so many questions.

* are you using the right schema configured on Craft for this?
* Is the Gatsby helper plugin set up?
* Have you enabled all the things needed in the schema?

**Comment by andris-sevcenko** [comment]
Closing this as the original issue has been solved.
