### ISSUE TITLE
Random number of entries returned

### ISSUE THREAD

**Issue by andreasottosson** [craftcms/gatsby-source-craft#42]
Hi!

We have one entry type with 279 entries that returns a completely random number of entries when queried from Gatsby. Craft´s built in GraphiQL always returns all 279. We can run `gatsby develop` and get 133, then run `gatsby clean`, run `gatsby develop` again and get 200, 179, 249 and so on. Completely random. This data in Craft is imported from a CSV file using Feed Me. I have cleared all caches in Craft and also re-saved all entries using the CLI and tried disabling / enabling all those entries.

This also happens when running `gatsby build`, we added a console.log to show the number of entries in the build log.

Any ideas what we are missing or how to debug this issue?

**Comment by andris-sevcenko** [comment]
@andreasottosson can you check if the resolution used [here](https://github.com/craftcms/gatsby-source-craft/issues/21) fixes this for you?

**Comment by andreasottosson** [comment]
@andris-sevcenko oh man, thanks! We tried searching but missed this old issue.

So the solution was, https://github.com/craftcms/gatsby-source-craft/issues/21#issuecomment-768407377

**Comment by andris-sevcenko** [comment]
Awesome!
