### ISSUE TITLE
The `sourceNodes` lifecycle fails after upgrading to the 2.0.2 patch.

### ISSUE THREAD

**Issue by sandren** [craftcms/gatsby-source-craft#44]
### Description
Upgrading from `2.0.1` to `2.0.2` results in an error during `gatsby develop` which causes all queries to return `null`:

```
"gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

Failed to execute query LIST_about_about_Entry.
Errors:
Unknown argument "status" on field "entry" of type "Query".

  468 |     if (remoteConfigVersion !== localConfigVersion || !localContentUpdateTime) {
  469 |         reporter.info("Cached content is unavailable or outdated, sourcing _all_ nodes.");
> 470 |         await sourceAllNodes(config);
      |         ^
  471 |     }
  472 |     else {
  473 |         reporter.info(`Craft config version has not changed since last sourcing. Checking for content changes since "${localContentUpdateTime}".`);

File: node_modules/gatsby-source-craft/gatsby-node.js:470:9



  Error: Failed to execute query LIST_about_about_Entry.
  Errors:
  Unknown argument "status" on field "entry" of type "Query".
  ```

### Steps to reproduce

1. upgrade `gatsby-source-craft` from any version to `2.0.2`
2. run `gatsby develop`

### Additional info

- Craft version: Craft Pro 3.6.17
- PHP version: 7.3.27
- Database driver & version: 	MySQL 5.5.5
- Plugins & versions: Gatsby Helper 1.0.3

**Comment by andris-sevcenko** [comment]
@sandren sounds like not everything is enabled for the Gatsby schema that should be enabled. Have you seen [this issue](https://github.com/craftcms/gatsby-source-craft/issues/37#issuecomment-855720728)?

**Comment by sandren** [comment]
> @sandren sounds like not everything is enabled for the Gatsby schema that should be enabled. Have you seen [this issue](https://github.com/craftcms/gatsby-source-craft/issues/37#issuecomment-855720728)?

Oh, I didn't know those had to be enabled. Doing so resolved the issue for me. Thanks! 😀
