### ISSUE TITLE
Structure entries in Gatsby do not return "children"

### ISSUE THREAD

**Issue by stephenfrank** [craftcms/gatsby-source-craft#46]
### Description

Structure entries do not return "children" as they do in the Craft GraphQL implementation.

I understand this might not be a bug but a platform limitation in transforming Craft entries into the Gatsby node graph but I feel it would be helpful to a lot of people if this functionality was available.

### Steps to reproduce

Any query on structure elements shows the `children` prop and all the associated interfaces but does not yield any results.

```graphql
query MyQuery {
  allCraftStructuredPagesContentPageEntry {
    nodes {
      children {
        id
      }
    }
  }
}
```

```json
{
  "data": {
    "allCraftStructuredPagesContentPageEntry": {
      "nodes": [
        {
          "children": []
        },
        {
          "children": []
        }
    ]
}
```

### Additional info

- Craft version: 3.6.16
- Gatsby helper: 1.0.3

**Comment by andris-sevcenko** [comment]
`children` is a field that is resolved dynamically by Craft, so is not available when querying Gatsby. You'll have to use [custom fragments](https://github.com/craftcms/gatsby-source-craft#customizing-generated-fragments) to make this work.

Here's some more reading for insight:
* https://github.com/craftcms/gatsby-source-craft/issues/33
* https://github.com/craftcms/gatsby-source-craft/issues/22
* https://github.com/craftcms/gatsby-source-craft/issues/16 (less applicable, but a decent overview on the whole Craft-Gatsby process)
