### ISSUE TITLE
Gatsby Cloud builds fail often via webhook and manual rebuilds

### ISSUE THREAD

**Issue by emson-digital** [craftcms/gatsby-source-craft#49]
### Description
Having some very consistent, but inconsistent errors. Most of the time I can run "Clear Cache and Rebuild" and the site will rebuild without error, but not always. Almost always if a rebuild is triggered by webhook it will fail, but very rarely it will succeed. 

If I run local builds 'Gatsby Develop' I never get a failure. But those are never triggered by webhook.

![image](https://user-images.githubusercontent.com/80485500/131732357-48cf1a81-3b23-42a5-a6f3-74e001212351.png)

**Error is sometimes:**

**Triggered by Gatsby Build webhook**
Build failed for branch staging
Failed after 0:10

Raw logs
"gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

Cannot read property 'map' of null

488 |         // Create the sourcing node events
  489 |         const nodeEvents = [
> 490 |             ...updatedNodes.map(entry => {
      |                             ^
  491 |                 return {
  492 |                     eventName: 'UPDATE',
  493 |                     remoteTypeName: entry.nodeType,

**Error is sometimes:** 

**Triggered by Gatsby Build webhook**
Build failed for branch staging
Failed after 0:19

Raw logs
"gatsby-source-craft" threw an error while running the onPreBootstrap lifecycle:

request to https://[redacted].com/api failed, reason: getaddrinfo EAI_AGAIN [redacted].com

For more details see https://gatsby.dev/issue-how-to

### Steps to reproduce

1. Make an edit in the CMS.
2. Save
3. Wait for error message in Gatsby Cloud.
![image](https://user-images.githubusercontent.com/80485500/131731190-6e25c4b0-8b56-4335-9f2f-77a35bd5feca.png)
or
![image](https://user-images.githubusercontent.com/80485500/131733079-d0ee42b1-59a2-44f9-ac52-b5a2a25e222b.png)

### Additional info

- Craft version:  3.7.11
- PHP version: 7.4.14
- Database driver & version: MySQL 5.7.29
- Plugins & versions:
Gatsby Helper
1.0.4
Plugin for enabling support for the Gatsby Craft CMS source plugin.

Google Cloud Storage
1.4.1
Google Cloud Storage integration for Craft CMS

Incognito Field
1.2.0
PlainText drop-in replacement that can be set to disabled, hidden or readonly.

Navigation
1.4.21
A Craft CMS plugin to create navigation menus for your site.

Neo
2.11.9
A Matrix-like field type that uses existing fields

Redactor
2.8.8
Edit rich text content in Craft CMS using Redactor by Imperavi.

SEOmatic
3.4.6
SEOmatic facilitates modern SEO best practices & implementation for Craft CMS 3. It is a turnkey SEO system that is comprehensive, powerful, and flexible.

Webhooks

### Additional Info:

![image](https://user-images.githubusercontent.com/80485500/131732537-031386c7-d21a-460f-aa92-c4d4d712ebc7.png)

**Comment by andris-sevcenko** [comment]
Can you check Craft logs? The first error would happen if Craft did not return an array there for the GraphQL query, however, it's not possible unless some error occurs which just throws the entire query off (https://github.com/craftcms/gatsby-helper/blob/main/src/gql/resolvers/UpdatedNode.php#L29).

The second error is a generic network DNS lookup error that is not something that would be related to Craft.(https://www.codingdefined.com/2015/06/nodejs-error-errno-eaiagain.html)

**Comment by glitton** [comment]
Hello,
Adding more details on this issue.  We see that the error occurs when deleting nodes.  2 examples are below.

`16:27:29 PM:
ERROR "gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

16:27:29 PM:
      |         ^

16:27:29 PM:
> 512 |         await sourceNodeChanges(config, { nodeEvents });

16:27:29 PM:
  513 |     }

16:27:29 PM:
  514 |     await cache.set(`CRAFT_CONFIG_VERSION`, remoteConfigVersion);

16:27:29 PM:
  511 |         // And source, if needed

16:27:29 PM:
  515 |     await cache.set(`CRAFT_LAST_CONTENT_UPDATE`, remoteContentUpdateTime);

16:27:29 PM:
  

16:27:29 PM:
16:27:29 PM:
  Error: Unknown type contentBuilder_faq_BlockType

16:27:29 PM:
    [www]/[gatsby-graphql-source-toolkit]/src/source-nodes/node-actions/delete-n    odes.ts:10:13

16:27:29 PM:
  - delete-nodes.ts:10 Object.deleteNodes

16:27:29 PM:`

`16:35:36 PM:
info Sourcing changes for 89 nodes.

16:35:36 PM:
ERROR "gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

16:35:36 PM:
Unknown type contentBuilder_faq_BlockType

16:35:36 PM:
  511 |         // And source, if needed

16:35:36 PM:
      |         ^

16:35:36 PM:
> 512 |         await sourceNodeChanges(config, { nodeEvents });

16:35:36 PM:
  510 |         }

16:35:36 PM:
  513 |     }

16:35:36 PM:
  514 |     await cache.set(`CRAFT_CONFIG_VERSION`, remoteConfigVersion);

16:35:36 PM:
  515 |     await cache.set(`CRAFT_LAST_CONTENT_UPDATE`, remoteContentUpdateTime);

16:35:36 PM:
  Error: Unknown type contentBuilder_faq_BlockType

16:35:36 PM:
16:35:36 PM:
  

16:35:36 PM:
    [www]/[gatsby-graphql-source-toolkit]/src/source-nodes/node-actions/delete-n    odes.ts:10:13

16:35:36 PM:
  - delete-nodes.ts:10 Object.deleteNodes

16:35:36 PM:
  

16:35:36 PM:
  - source-node-changes.ts:34 sourceNodeChanges

16:35:36 PM:
    [www]/[gatsby-graphql-source-toolkit]/src/source-nodes/source-node-changes.t    s:34:9

16:35:36 PM:
  - gatsby-node.js:512 Object.exports.sourceNodes

16:35:36 PM:`

**Comment by emson-digital** [comment]
More to add. Previews build as expected and never seem to fail. Just when I save the entry through the CMS and trigger a build. 

Preview with expected changes. In this case I added text to the description field and moved the "Embed" block below the Callout Block.
![image](https://user-images.githubusercontent.com/80485500/132574394-35821817-07d1-468d-a0e0-3ec620f8913e.png)

Result in Gatsby Cloud with error message.
![image](https://user-images.githubusercontent.com/80485500/132574553-533064d9-72a7-497c-b4c9-eacd63dfd366.png)

**Comment by emson-digital** [comment]
![image](https://user-images.githubusercontent.com/80485500/132574919-f34c1e6e-c7c3-4d6f-ac3f-762dec00b1ad.png)

**Comment by emson-digital** [comment]
Clearing cache and rebuilding on Gatsby side allowed for a clean build. 

![image](https://user-images.githubusercontent.com/80485500/132576000-ae0505aa-f914-4a4a-a03a-6b7208b807c5.png)

**Comment by andris-sevcenko** [comment]
This is an issue with the Neo plugin. It's not really a bug, it's just that support for Gatsby Helper/source plugin has not been added yet. I've opened an issue there and also provided a fix, so this should be resolved rather quickly.

**Comment by ttempleton** [comment]
Should be resolved with Neo 2.11.11.1, thanks again @andris-sevcenko for bringing this to our attention.

**Comment by andris-sevcenko** [comment]
@emson-digital can you update to Neo 2.11.11.1 and give it another shot?

**Comment by emson-digital** [comment]
@andris-sevcenko that seems to have resolved it. I haven't been able to produce a build error today. Much appreciated to you and @ttempleton !
