### ISSUE TITLE
changes are ignored when using multiple sites

### ISSUE THREAD

**Issue by mmorkt** [craftcms/gatsby-source-craft#53]
Using multiple sites:
When changing an entry in Craft CMS. GatsbyJS dosn’t make the changes. I have to preform a "gatsby clean” to see my changes. Turn the extra site off and it will build. 

@andris-sevcenko 

Steps to reproduce

- Save entry
- run "gatsby build"
- turn it off the extra site and the page will build

Additional info

- Craft version: 3.7.16
- PHP version: 7.3.31
- Database driver & version: MySQL 5.6.51
- Plugins & versions:
- Cloner: 1.2.2
- Gatsby Helper: 1.0.6
- Redactor: 2.8.8
- Formie: 1.4.21.1
- Smith: 1.1.14
- Spoon: 3.6.1
- Sprout Notes: 2.2.3
- Tags: 1.0.9

**Comment by andreasottosson** [comment]
Hello again Andris! 😁

So the output looks correct,

```
info Checking Craft config version.
info Craft config version has not changed since last sourcing. Checking for content changes since "2021-10-20 07:58:48".
info Sourcing changes for 4 nodes.
success Checking for changed pages - 0.001s
success source and transform nodes - 1.444s
success building schema - 6.310s
success createPages - 0.185s
info Total nodes: 1305, SitePage nodes: 101 (use --verbose for breakdown)
success Checking for changed pages - 0.006s
success update schema - 1.771s
success onPreExtractQueries - 0.000s
success extract queries from components - 1.890s
success write out requires - 0.002s
success Writing page-data.json files to public directory - 0.019s - 0/96 4944.91/s

```

But no changes are reflected on the site until we run "gatsby clean" first. Then the changes are there on the next run of "gatsby develop". Our site as you know is a multisite but now we only have the default site active, this behavior is the same either way. Seems like incremental changes are not picked up. https://github.com/craftcms/gatsby-helper/issues/16 seems to have similar issues.

Just let me know if you need anything else from us.

// Andreas

**Comment by andreasottosson** [comment]
Nice work, as always! Thanks.
