### ISSUE TITLE
Add support to Gatsby v4

### ISSUE THREAD

**Issue by webrgp** [craftcms/gatsby-source-craft#55]
### Description
The plugin runs in dev mode, just throwing:
```sh
warn Plugin gatsby-source-craft is not compatible with your gatsby version 4.0.0 - It requires gatsby@^3.0.0
```

But when I try to build, I get:
```sh
success onPostBootstrap - 0.136s
info bootstrap finished - 30.937s
success write out requires - 0.007s

 ERROR #11321  PLUGIN

"gatsby-source-craft" threw an error while running the createSchemaCustomization lifecycle:

ENOENT: no such file or directory, open '/Code/craftcms-gatsby-website/node_modules/
gatsby-source-craft/.cache/craft-graphql-documents/home_home_Entry.graphql'



  Error: ENOENT: no such file or directory, open '/Code/craftcms-gatsby-website/node
  _modules/gatsby-source-craft/.cache/craft-graphql-documents/home_home_Entry.graphql'


 ERROR #11321  PLUGIN

"gatsby-source-craft" threw an error while running the createSchemaCustomization lifecycle:

ENOENT: no such file or directory, open '/Code/craftcms-gatsby-website/node_modules/
gatsby-source-craft/.cache/craft-graphql-documents/home_home_Entry.graphql'



  Error: ENOENT: no such file or directory, open '/Code/craftcms-gatsby-website/node
  _modules/gatsby-source-craft/.cache/craft-graphql-documents/home_home_Entry.graphql'


 ERROR #11321  PLUGIN

"gatsby-source-craft" threw an error while running the createSchemaCustomization lifecycle:

ENOENT: no such file or directory, open '/Code/craftcms-gatsby-website/node_modules/
gatsby-source-craft/.cache/craft-graphql-documents/home_home_Entry.graphql'



  Error: ENOENT: no such file or directory, open '/Code/craftcms-gatsby-website/node
  _modules/gatsby-source-craft/.cache/craft-graphql-documents/home_home_Entry.graphql'


 ERROR

UNHANDLED REJECTION Worker exited before finishing task



  Error: Worker exited before finishing task

  - index.js:112 ChildProcess.<anonymous>
    [craftcms-gatsby-website]/[gatsby-worker]/dist/index.js:112:45

  - child_process.js:282 Process.ChildProcess._handle.onexit
    internal/child_process.js:282:12


not finished Building production JavaScript and CSS bundles - 2.184s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce

1. Have Craft running on Nitro
2. Build Gatsby Site that 

### Additional info

- Craft version: 3.7.17.1
- Nitro version: 2.0.8
- PHP version: 8.0.11
- Database driver & version: MySQL 5.7.33
- Plugins & versions:
  - Expanded Singles	1.1.4
  - Gatsby Helper	1.0.7
  - Imager X	v3.5.3
  - Navigation	1.4.21
  - Redactor	2.8.8
  - SEOmatic	3.4.17
  - Super Table	2.6.8
  - Typed link field	1.0.25

- Gatsby version: 4.0
  - gatsby-source-craft version: 2.0.4

```js
{
  resolve: `gatsby-source-craft`,
  options: {
    fragmentsDir: `${__dirname}/craft-fragments/`,
    debugDir: `${__dirname}/craft-debug/`,
    craftGqlToken: process.env.CRAFTGQL_TOKEN,
    craftGqlUrl: process.env.CRAFTGQL_URL,
    typePrefix: `Craft_`,
  },
},
```

**Comment by webrgp** [comment]
After some digging, the issue is related to the `debugDir` config option. On build, it fails here:

```sh
ENOENT: no such file or directory, open '/Code/craftcms-gatsby-website/node_modules/
gatsby-source-craft/.cache/craft-graphql-documents/home_home_Entry.graphql'
```

The `.cache/craft-graphql-documents` is overrided by `debugDir`, but for some reason, on build time, it looks at `.cache/craft-graphql-documents`.

Not using the `debugDir` solves my immediate issue, but doesn't fix the problem.

**Comment by alipetarian** [comment]
> @acarioca The latest version does work with Gatsby 4, with a few annoyances, but it does work wink

Would you please explain how we can get this working. We dont really want to shift Gatsby v3. We are also getting same error.

**Comment by webrgp** [comment]
Any movement on this?

**Comment by sandren** [comment]
The Gatsby v4 compatible version can be installed like this until there is an official release:

`yarn install https://github.com/craftcms/gatsby-source-craft#gatsby-v4`

**Comment by webrgp** [comment]
@sandren I appreciate the reply, but I am already using the `gatsby-source-craft#gatsby-v4` version on a few projects and I am getting hesitant to keep going this route because of the lack of activity.

I wish I had a bit more visibility into what the Craft's team roadmap for supporting Gatsby, so I could contribute more to it.

**Comment by sandren** [comment]
> I am already using the `gatsby-source-craft#gatsby-v4` version on a few projects and I am getting hesitant to keep going this route because of the lack of activity.
> 
> I wish I had a bit more visibility into what the Craft's team roadmap for supporting Gatsby, so I could contribute more to it.

@webrgp I'm concerned about the lag between Gatsby releases and compatible gatsby-source-craft updates as well. I think adding some information for Craft + Gatsby on the official Craft CMS website would go a long way. Otherwise it kind of feels like we're an unsupported use case. 😐

**Comment by andris-sevcenko** [comment]
I had to prioritize Craft 4 as it's approaching a beta release and it's just too many dishes for me and sometimes a few of them stop spinning. I can definitely tell you that you are not an unsupported use case but that's on me and my lack of communication, for which I apologize.

As far as Gatsby 4 goes, you can use this plugin as mentioned above. There hasn't been an official release because we're still downloading local files for Assets in a way that's not encouraged. Currently, this plugin downloads the Assets when they are being queried for when building the site, however, this is not compatible with Gatsby's "builds should be super fast" approach, so the actual file download has to be moved to the site sourcing stage, which is problematic, as there is no indication on which assets will be needed at the site build stage. The only approach really left is to source _all_ the assets and cache them intelligently.

All in all it's a bit of an undertaking and currently I can circle back to that after I get everything in order for Craft 4 beta release that depends on me.

Sorry for making you wait, people, but I just want to underline that you are not a "second class citizen" or anything like that - it's really a matter of balancing what resources we have available :/

**Comment by webrgp** [comment]
> 

Thanks for the update! I can appreciate having to prioritize different tasks, and I want to reiterate that I can contribute more, but the lack of documentation in this repo makes it harder to do it (like the typescript setup, linting, tests, etc). 

I know the assets piece is a hard nut to crack, but I feel part of the issue is because native image transforms in Craft isn't robust enough. In one project I've dropped the `gatsby-source-craft` plugin entirely for `gatsby-source-graphql` and I've used the [craft-jitter](https://github.com/codewithkyle/craft-jitter) to perform url based transforms on the server.

Will that improve in Craft 4?

**Comment by andris-sevcenko** [comment]
> Will that improve in Craft 4?

Funny you should ask - https://github.com/craftcms/cms/pull/10367

Craft 4 will have an image transform driver layer and we're aiming to provide a 1st party Imgix transform driver. It will be much simpler to add support for more transform drivers that are more robust than the one provided by Craft. I currently don't see any obstacles to having a transform driver that utilizes `sharp` image transforms, too.

Once Craft 4 beta is out, it's likely that we'll be able to sidestep the assets piece altogether!

**Comment by andris-sevcenko** [comment]
> lack of documentation in this repo makes it harder to do it (like the typescript setup, linting, tests, etc).

Sorry to say it's all very primitive. There's a `tsconfig.json` file in the repo that I use. For testing, I point the config file to an existing Craft site with the Gatsby Helper plugin installed and then fire up a Gatsby develop instance, to see if it sources correctly. It's primitive, but that's what I got currently :/

**Comment by sgtpenguin** [comment]
`yarn add https://github.com/craftcms/gatsby-source-craft#gatsby-v4` 
doesn't seem to work anymore

> https://github.com/craftcms/gatsby-source-craft/tree/gatsby-v4
gives 404

Is there a way to install a working version for Gatsby 4?

**Comment by aronkerr** [comment]
Is there an update on this at all? Another year has passed and this is now 2 major versions behind Gatsby. I have been using gatsby-source-graphql but I am running into issues getting previews to work with Craft 4 and Craft technical support is pushing me to switch to this sourcing plugin instead. I am extremely hesitant to do so given the lack of movement here.

**Comment by brianjhanson** [comment]
Support for Gatsby v4 was added in [3.0 of this plugin](https://github.com/craftcms/gatsby-source-craft/blob/main/CHANGELOG.md#300---2022-04-14). It looks like this issue was just never closed out. Overall the changes to support v4 [were pretty minor](https://github.com/craftcms/gatsby-source-craft/compare/v2.0.7...v3.0.0).

If anyone is running into issues with v4 support please open new issues for specific bugs.
