### ISSUE TITLE
Error while sourcing with "Allow listing non-live and otherwise inactive elements." disabled in Schema

### ISSUE THREAD

**Issue by andreasottosson** [craftcms/gatsby-source-craft#61]
### Description
Guess who's back.. na na na.. back again ;)

Gatsby build fails when this is unchecked,

```
 ERROR #11321  PLUGIN

"gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

Failed to execute query LIST_forhandlere_forhandler_Entry.
Errors:
Unknown argument "status" on field "entry" of type "Query".

  510 |     if (remoteConfigVersion !== localConfigVersion || !localContentUpdateTime) {
  511 |         reporter.info("Cached content is unavailable or outdated, sourcing _all_ nodes.");
> 512 |         await sourceAllNodes(config);
      |         ^
  513 |     }
  514 |     else {
  515 |         reporter.info(`Craft config version has not changed since last sourcing. Checking for content changes since "${localContentUpdateTime}".`);

File: node_modules/gatsby-source-craft/gatsby-node.js:512:9
```

From Craft's `web.log`:

```
2021-12-02 11:40:33 [-][-][-][error][GraphQL\Error\Error] Unknown argument "status" on field "entry" of type "Query".

GraphQL (2:35)
1: query NODE_produkter_glasdore_Entry($id: [QueryArgument], $siteId: [QueryArgument]) {
2:   entry(id: $id, siteId: $siteId, status: null) {
                                     ^
3:     remoteTypeName: __typename
```

### Steps to reproduce

1. Uncheck "Allow listing non-live and otherwise inactive elements." in your Craft GQL schema settings
2. Source data
3. Pull your hair out ;)

### Additional info

- Craft version: 3.7.23
- PHP version: 7.3.31
- Database driver & version: MySQL 5.6.51
- Plugins & versions:
Cloner	1.2.2
Freeform	3.12.7
Gatsby Helper	1.1.0
Redactor	2.8.8
Smith	1.1.14
Spoon	3.6.1
Sprout Notes	2.2.3
Tags	1.0.9

**Comment by andris-sevcenko** [comment]
That is the [expected behavior](https://github.com/craftcms/gatsby-source-craft/issues/37#issuecomment-855720728), as Live Preview on a Gatsby site will fail otherwise. Also, there's a search option for the repository :)
