### ISSUE TITLE
Query to return `lastUpdateTime` can be mistakenly cached

### ISSUE THREAD

**Issue by monachilada** [craftcms/gatsby-source-craft#8]
In reference to this line:
https://github.com/craftcms/gatsby-source-craft/blob/89db4153c8af134d2d6294c3e943af3f44b162ea/gatsby-node.js#L443

It appears the results of this query can be cached, meaning the timestamp of the latest updated returned can be inaccurate. The follow-on effect of this is that the list of changed and deleted nodes fetched here: 
https://github.com/craftcms/gatsby-source-craft/blob/89db4153c8af134d2d6294c3e943af3f44b162ea/gatsby-node.js#L460-L463
will be too long and have references to nodes that were never present in the initial build. Finally, arriving at this line:
https://github.com/craftcms/gatsby-source-craft/blob/89db4153c8af134d2d6294c3e943af3f44b162ea/gatsby-node.js#L492
will throw an error, since references in the list of `nodeEvents` pointing to nodes not existing locally will throw errors like this: 
<img width="749" alt="Screen Shot 2020-11-15 at 20 20 21" src="https://user-images.githubusercontent.com/613183/99194499-05b55880-2780-11eb-8aa5-f4476d7763f5.png">

Suggestion would be to potentially inject a random variable in the query to ensure up to date results?

**Comment by monachilada** [comment]
Added a PR [here](https://github.com/craftcms/gatsby-source-craft/pull/9). It's not super pretty and might not match code style wise to similar cases in the rest of Craft's codebase, so there might be a better solution.

**Comment by andris-sevcenko** [comment]
We've been toying with allowing bypassing cache with a header for a while now. Seems like it needs to happen sooner rather than later and then Gatsby plugin can just use that to bypass cache.

**Comment by monachilada** [comment]
Sounds like a much more elegant solution.

**Comment by andris-sevcenko** [comment]
Technically, not resolved yet. Support for this is in Craft. Need to wait for a Craft release, then fully resolve this.

**Comment by monachilada** [comment]
I added a PR here that I think should fix it. Hopefully it's helpful? https://github.com/craftcms/gatsby-source-craft/pull/11

**Comment by brandonkelly** [comment]
Gatsby Helper 1.0.0-beta.2 is out now with that change. Thanks again!
